ignore-dirs:
  - "tmp"
  - "coverage"
ignores:
  - "@babel/*"
  - "eslint*"
  - "@typescript-eslint/*"
  - "@graphql-codegen/*"
  - "@babel/runtime"
  - "@scrlk/eslint-config"
  - "babel-eslint"
  - "sass"
  - "styled-jsx"
  - "url-loader"
  - "workbox-core"
  - "assets"
  - "components"
  - "generated"
  - "gql"
  - "pages"
  - "service"
  - "ts"
  - "utils"
