image: node:14
before_script:
  - npm ci

stages:
  - prepare
  - test
  - build
  - deploy

prepare-fonts:
  stage: prepare
  before_script: []
  image: scrlk/woff2
  needs: []
  script:
    - ./generateFonts.sh
  artifacts:
    paths:
      - public/static/fonts

test:
  stage: test
  needs: []
  script:
    - npm run test

build:
  stage: build
  script:
    - npm run build
  needs:
    - prepare-fonts
  artifacts:
    paths:
      - .next
      - public/sw.js

include:
  - project: 'Tymek/CI'
    file: '/.dockerize.yml'
