image: node:14
before_script:
  - npm ci

stages:
  - test
  - build
  - deploy

test:
  stage: test
  script:
    - npm run test

build:
  stage: build
  script:
    - npm run build
  needs: []
  artifacts:
    paths:
      - .next
      - public/sw.js

prepare-fonts:
  stage: build
  image: scrlk/woff2
  needs: []
  script:
    - ./generateFonts.sh
  artifacts:
    paths:
      - public/static/fonts

include:
  - project: 'Tymek/CI'
    file: '/.dockerize.yml'
