version: '3.6'
services:
  next:
    image: node:14
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./:/srv
    working_dir: /srv
    tty: true
    environment:
      TERM: xterm-256color
      ACTION_SECRET_ENV: "${ACTION_SECRET_ENV:-0}"
    command: npm run dev

  postgres:
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
    tty: true
    environment:
      TERM: xterm-256color

  hasura:
    restart: unless-stopped
    ports:
      - "8080:8080"
    tty: true
    environment:
      TERM: xterm-256color
      HASURA_GRAPHQL_CORS_DOMAIN: "*"
      HASURA_GRAPHQL_CONSOLE_ASSETS_DIR: "/srv/console-assets"
      HASURA_GRAPHQL_ENABLE_CONSOLE: "${HASURA_GRAPHQL_ENABLE_CONSOLE:-true}"
      HASURA_GRAPHQL_ADMIN_SECRET: "${HASURA_GRAPHQL_ADMIN_SECRET:-0}"
      HASURA_GRAPHQL_DEV_MODE: "true"
      ACTION_SECRET_ENV: "${ACTION_SECRET_ENV:-0}"

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - 5050:80
    tty: true
    environment:
      TERM: xterm-256color
      PGADMIN_DEFAULT_EMAIL: "admin@localhost"
      PGADMIN_DEFAULT_PASSWORD: "0"
    networks:
      - wan
      - lan

networks:
  wan:
    external: false
