version: '3.6'
services:
  next:
    image: "${APP_DOCKER_IMAGE:-registry.gitlab.com/scrlk/zdbwc}"
    restart: always
    depends_on:
      - hasura
    environment:
      HASURA_ACTION_SECRET: "${HASURA_ACTION_SECRET}"
      ANALYTICS_SECRET: "${ANALYTICS_SECRET}"
      NEXT_PUBLIC_ANALYTICS_ID: "${NEXT_PUBLIC_ANALYTICS_ID}"
      NEXT_PUBLIC_ANALYTICS_DOMAINS: "${NEXT_PUBLIC_ANALYTICS_DOMAINS}"
    networks:
      - wan
      - lan
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:${DOMAIN},www.${DOMAIN}
      - traefik.port=3000
      - traefik.docker.network=wan
      - traefik.frontend.headers.SSLRedirect=true
      - traefik.frontend.headers.SSLHost=${DOMAIN}
      - traefik.frontend.headers.SSLForceHost=true
      - com.ouroboros.enable=true

  postgres:
    image: postgres:12
    restart: always
    volumes:
      - ./.data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-postgres}"
    networks:
      - lan

  hasura:
    image: "hasura/graphql-engine:${HASURA_VERSION:-v1.3.0}.cli-migrations"
    depends_on:
      - postgres
    restart: always
    environment:
      HASURA_GRAPHQL_CORS_DOMAIN: "https://${DOMAIN:-localhost}, https://*.${DOMAIN:-localhost}"
      HASURA_GRAPHQL_DATABASE_URL: "${HASURA_GRAPHQL_DATABASE_URL:-postgres://postgres:postgres@postgres:5432/postgres}"
      HASURA_GRAPHQL_ENABLE_CONSOLE: "${HASURA_GRAPHQL_ENABLE_CONSOLE:-false}"
      HASURA_GRAPHQL_ENABLE_TELEMETRY: "${HASURA_GRAPHQL_ENABLE_TELEMETRY:-false}"
      HASURA_GRAPHQL_ADMIN_SECRET: "${HASURA_GRAPHQL_ADMIN_SECRET}"
      HASURA_GRAPHQL_AUTH_HOOK: "http://next:3000/api/auth-webhook"
      HASURA_ACTION_SECRET: "${HASURA_ACTION_SECRET}"
    networks:
      - wan
      - lan
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:api.${DOMAIN}
      - traefik.port=8080
      - traefik.docker.network=wan
      - traefik.frontend.headers.SSLRedirect=true
      - traefik.frontend.headers.SSLHost=api.${DOMAIN}
      - traefik.frontend.headers.SSLForceHost=true

networks:
  lan:
    external: false
  wan:
    external: true
