version: '3.6'
services:
  postgres:
    image: postgres:12
    restart: always
    volumes:
      - ./.data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-postgres}"
    networks:
      - lan

  graphql-engine:
    image: "hasura/graphql-engine:${HASURA_VERSION:-v1.3.0-beta.1}.cli-migrations"
    depends_on:
      - postgres
    restart: always
    environment:
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: anonymous
      HASURA_GRAPHQL_CORS_DOMAIN: "https://${DOMAIN:-localhost}, https://*.${DOMAIN:-localhost}"
      HASURA_GRAPHQL_DATABASE_URL: "${HASURA_GRAPHQL_DATABASE_URL:-postgres://postgres:postgres@postgres:5432/postgres}"
      HASURA_GRAPHQL_ENABLE_CONSOLE: "${HASURA_GRAPHQL_ENABLE_CONSOLE:-false}"
      HASURA_GRAPHQL_ENABLE_TELEMETRY: "${HASURA_GRAPHQL_ENABLE_TELEMETRY:-false}"
      HASURA_GRAPHQL_ADMIN_SECRET: "${HASURA_GRAPHQL_ADMIN_SECRET}"
      HASURA_GRAPHQL_AUTH_HOOK_MODE: POST
      HASURA_GRAPHQL_AUTH_HOOK: "${HASURA_GRAPHQL_AUTH_HOOK}"
    networks:
      - wan
      - lan

networks:
  lan:
    external: false
  wan:
    external: true
